title: mazrica.fm
description: >-
  株式会社マツリカ社員による公式Podcast
baseurl: ""
url: ""
hashtag: マツリカfm
timezone: Asia/Tokyo
include:
  - _pages
plugins:
  - jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
sass:
  style: compact
  sass_dir: css